# Generated by Django 5.1 on 2024-10-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='count_views',
            new_name='views_count',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(default=True, help_text='Введите текст', verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='blog/image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(help_text='Введите slug', max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Введите заголовок', max_length=100, verbose_name='Заголовок'),
        ),
    ]
