# Generated by Django 5.1 on 2024-09-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blogpost_remove_product_manufactured_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
