# Generated by Django 5.1 on 2024-10-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Версия продукта', 'verbose_name_plural': 'Версии продукта'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='version',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='version',
            name='version_number',
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(blank=True, help_text='Введите дату производства продукта', null=True, verbose_name='Дата производства продукта'),
        ),
    ]
