# Generated by Django 5.1 on 2024-10-17 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_options_alter_version_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Укажите владельца продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фото продукта', null=True, upload_to='catalog/photo', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Счетчик просмотров'),
        ),
        migrations.AddField(
            model_name='version',
            name='active',
            field=models.BooleanField(default=False, help_text='Введите признак текущей версии продукта', verbose_name='Признак текущей версии'),
        ),
        migrations.AddField(
            model_name='version',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Введите категорию продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_product', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.CharField(default=2, help_text='Введите наименование продукта', max_length=100, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='version_num',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Укажите номер версии продукта', null=True, verbose_name='Номер версии'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(help_text='Введите описание категории', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите наименование категории', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Введите категорию продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(help_text='Введите дату создания продукта', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Введите описание продукта', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Введите наименование продукта', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(blank=True, help_text='Введите дату последнего изменения продукта', null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='catalog.product', verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(blank=True, default='', help_text='Введите наименование версии продукта', max_length=100, null=True, verbose_name='Наименование версии'),
        ),
    ]
