# Generated by Django 5.1 on 2024-11-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_owner_product_photo_product_views_counter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'permissions': [('can_change_product_description', 'Может изменять описание продукта'), ('can_change_product_category', 'Может изменять категорию продукта'), ('can_change_product_status', 'Может изменять статус публикации продукта')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
